# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'my_task.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(648, 537)
        self.task_one = QtWidgets.QLabel(Dialog)
        self.task_one.setGeometry(QtCore.QRect(130, 30, 501, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.task_one.setFont(font)
        self.task_one.setObjectName("task_one")
        self.task_two = QtWidgets.QLabel(Dialog)
        self.task_two.setGeometry(QtCore.QRect(130, 120, 501, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.task_two.setFont(font)
        self.task_two.setObjectName("task_two")
        self.task_trhee = QtWidgets.QLabel(Dialog)
        self.task_trhee.setGeometry(QtCore.QRect(130, 210, 491, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.task_trhee.setFont(font)
        self.task_trhee.setObjectName("task_trhee")
        self.task_four = QtWidgets.QLabel(Dialog)
        self.task_four.setGeometry(QtCore.QRect(130, 280, 501, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.task_four.setFont(font)
        self.task_four.setObjectName("task_four")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(130, 360, 501, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.go_home = QtWidgets.QPushButton(Dialog)
        self.go_home.setGeometry(QtCore.QRect(0, 0, 131, 31))
        self.go_home.setObjectName("go_home")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.task_one.setText(_translate("Dialog", "Task1"))
        self.task_two.setText(_translate("Dialog", "Task2"))
        self.task_trhee.setText(_translate("Dialog", "Task3"))
        self.task_four.setText(_translate("Dialog", "Task4"))
        self.label_5.setText(_translate("Dialog", "Task5"))
        self.go_home.setText(_translate("Dialog", "Go  home"))
